### ISSUE TITLE
Update Sign In Page

### ISSUE THREAD

**Issue by RiceWater** [aid8/Ascension#60]
- Redirect to the new Sign In Page
- set the necessary values
- set the necessary fields to readonly
- relocate Google api/redirect to this page

**Comment by aid8** [comment]
Fixed:
- Redirect to the new Sign In Page 
- relocate Google api/redirect to this page
- in #72

**Comment by aid8** [comment]
Fixed
- set the necessary fields to readonly
- relocate Google api/redirect to this page
- in #76 

Left todo:
- Make SignUpPage work (save student/teacher/ntdistributor data)

**Comment by aid8** [comment]
This issue is relocated in #78
