### ISSUE TITLE
Add StatusTitle Entity

### ISSUE THREAD

**Issue by aid8** [aid8/Ascension#88]
## Status Titles
Attributes:
- StatusTitle = ""
- StatusImage

**Comment by RiceWater** [comment]
This means that we will add a gender attribute, right?

**Comment by aid8** [comment]
> This means that we will add a gender attribute, right?

Yes, refer to issue #89

**Comment by RiceWater** [comment]
Noted, thank you.

> > This means that we will add a gender attribute, right?
> 
> Yes, refer to issue #89

Noted, thank you.

**Comment by aid8** [comment]
Fixed in #91, will be closed after adding this to the TestPage

**Comment by aid8** [comment]
Added to TestPage in #101
